// This file will be automatically generated by Payload CMS
// when you run `npm run payload generate:types`

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: 'admin' | 'user';
}

export interface Snack {
  id: string;
  name: string;
  description: string;
  price: number;
  category: 'chips' | 'candy' | 'cookies' | 'nuts' | 'crackers' | 'drinks';
  image?: string;
  available: boolean;
}

export interface Order {
  id: string;
  user?: string;
  items: {
    snack: string;
    quantity: number;
  }[];
  status: 'pending' | 'processing' | 'shipped' | 'completed' | 'cancelled' | 'refunded';
  totalAmount: number;
  subtotal: number;
  shippingCharge: number;
  orderDate: string;
}

export interface DeliverySettings {
  id: string;
  insideDhakaCharge: number;
  outsideDhakaCharge: number;
  freeDeliveryThreshold: number;
}